### ISSUE TITLE
Click on symbol type -> System.AccessViolationException

### ISSUE THREAD

**Issue by Symbai** [zodiacon/PdbView#1]
I opened a pdb file switched to the types tab and opened a large type (a class with a size of: 4526) which appears twice in list but with different indexes.

However the application immediately throws a System.AccessViolationException, the callstack in VS is empty. I believe it happens somewhere in Zodiacon.DebugHelp where no debug information exists.

I can view other classes but not this one. PDB file is over 300mb too large to share. Any ideas? Is there the source of Zodicon.DebugHelp available so I can try to look deeper into it?

**Comment by zodiacon** [comment]
Please share PDB file via Onedrive, dropbox or whatever.
I will take steps to share DebugHelp as well.

**Comment by zodiacon** [comment]
Just published DebugHelp repo.

**Comment by Symbai** [comment]
Thank you. Sadly the stacktrace is still empty. Here is the pdb file: https://mega.nz/#!qHw11CiK!j0s9IV5syvRXOQhWJNqiNQmVAZNMy7c0l6ZTFcMJfgk

1. Open the pdb file
2. Switch to types
3. Filter for "APrimalCharacter" 
4. Sort by size
5. Select the first biggest with index 494392

**Comment by Symbai** [comment]
I found the issue. The size of Child array in FindChildrenParams struct https://github.com/zodiacon/DebugHelp/blob/ddaf3365045de38150987e72810ca3bce2a2a35e/DebugHelp/Win32.cs#L141 is too less as the children count for this class is somewhat about 1,100. So if I just change it to something very huge like 4,000 it no longer crashes. Which makes sense as before it was trying to write children over the end of the fixed array.

I've taken a look at [MDSN ](https://docs.microsoft.com/en-us/windows/desktop/api/dbghelp/ns-dbghelp-_ti_findchildren_params) but they don't provide any information about the maximum size.  Are there any reasons to not use a large array size?

**Comment by zodiacon** [comment]
No reason except memory consumption... I guess I thought it was large enough ;)

**Comment by Symbai** [comment]
But its only one time memory consumption right? I'm not fully into the full source code yet.

**Comment by zodiacon** [comment]
Yes, increasing it should be fine.

**Comment by Symbai** [comment]
Cool, thanks for publishing DebugHelp otherwise I would have been lost :D
